name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *" # 7am UTC everyday

concurrency:
  group: ${{ github.event.pull_request && format('ci-pr-{0}', github.event.pull_request.number) || format('ci-push-main-{0}', github.sha) }}
  cancel-in-progress: true

jobs:
  ci:
    environment: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - name: "Cache Maven packages"
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build project"
        run: ./mvnw clean package

      - name: "Build image"
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "${{ vars.QUAY_REPOSITORY }}"
          tags: ${{ github.event.pull_request && format('pr-{0}', github.event.pull_request.number) || format('latest {0}', github.sha) }}
          containerfiles: |
            ./src/main/docker/Dockerfile.jvm

      - name: "Push To quay.io"
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: "${{ steps.build-image.outputs.image }}"
          tags: "${{ steps.build-image.outputs.tags }}"
          registry: "quay.io/${{ vars.QUAY_REPOSITORY_USER }}"
          username: "${{ vars.QUAY_USER }}"
          password: "${{ secrets.QUAY_PASSWORD }}"

      - name: "Print image names"
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

      - name: "Add comment to the PR"
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The image is available at: ${{ steps.push-to-quay.outputs.registry-path }}'
            })
